param(
    [switch]$Reset
)

$ErrorActionPreference = "Stop"

function Run-Compose {
    param([string[]]$Cmd)
    Write-Host ("docker compose " + ($Cmd -join " "))
    & docker compose @Cmd
    if ($LASTEXITCODE -ne 0) {
        throw ("docker compose " + ($Cmd -join " ") + " failed.")
    }
}

function Wait-ForDb {
    Write-Host "Waiting for MariaDB to accept connections..."
    for ($i = 0; $i -lt 60; $i++) {
        & docker compose exec -T db mysqladmin ping -h 127.0.0.1 -umagento -pmagento --silent *> $null
        if ($LASTEXITCODE -eq 0) {
            return
        }
        Start-Sleep -Seconds 2
    }
    throw "Database did not become ready in time."
}

function Ensure-ThemePreviewImage {
    Write-Host "Ensuring theme preview image exists..."
    & docker compose exec -T app php -r "if (!file_exists('app/design/frontend/Agency/hyva-demo/media/preview.jpg')) { @mkdir('app/design/frontend/Agency/hyva-demo/media', 0777, true); `$im=imagecreatetruecolor(10,10); `$bg=imagecolorallocate(`$im,240,240,240); imagefill(`$im,0,0,`$bg); imagejpeg(`$im,'app/design/frontend/Agency/hyva-demo/media/preview.jpg'); imagedestroy(`$im); }"
    if ($LASTEXITCODE -ne 0) {
        throw "Failed creating theme preview image."
    }
}

function Is-MagentoInstalled {
    & docker compose exec -T app sh -lc "test -f app/etc/env.php" *> $null
    return ($LASTEXITCODE -eq 0)
}

function Clear-InstallState {
    Write-Host "Clearing local Magento install state files..."
    if (Test-Path "app/etc/env.php") {
        Remove-Item "app/etc/env.php" -Force
    }
    # Keep this optional: some repos commit app/etc/config.php, but if present from
    # a prior install it can still be regenerated by setup:install.
    if (Test-Path "app/etc/config.php") {
        Remove-Item "app/etc/config.php" -Force
    }
}

function Apply-BrandingAndTheme {
    Write-Host "Applying theme + branding settings..."

    & docker compose exec -T db mysql -umagento -pmagento -D magento -e "UPDATE theme t JOIN theme p ON p.theme_path='Magento/luma' SET t.parent_id=p.theme_id WHERE t.theme_path='Agency/hyva-demo';" *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to align custom theme parent."
    }

    $themeId = (& docker compose exec -T db mysql -N -umagento -pmagento -D magento -e "SELECT theme_id FROM theme WHERE theme_path='Agency/hyva-demo' LIMIT 1;").Trim()
    if (-not $themeId) {
        throw "Could not resolve theme_id for Agency/hyva-demo."
    }

    $year = Get-Date -Format "yyyy"
    $copyright = "Copyright © $year Arshia. All rights reserved."

    & docker compose exec -T db mysql -umagento -pmagento -D magento -e "REPLACE INTO core_config_data (scope,scope_id,path,value) VALUES ('default',0,'design/theme/theme_id','$themeId');" *> $null
    if ($LASTEXITCODE -ne 0) { throw "Failed setting storefront theme." }

    & docker compose exec -T db mysql -umagento -pmagento -D magento -e "REPLACE INTO core_config_data (scope,scope_id,path,value) VALUES ('default',0,'general/store_information/name','Arshia Store');" *> $null
    if ($LASTEXITCODE -ne 0) { throw "Failed setting store name." }

    & docker compose exec -T db mysql -umagento -pmagento -D magento -e "REPLACE INTO core_config_data (scope,scope_id,path,value) VALUES ('default',0,'design/footer/copyright','$copyright');" *> $null
    if ($LASTEXITCODE -ne 0) { throw "Failed setting footer copyright." }

    & docker compose exec -T app bin/magento cache:clean config full_page block_html
    if ($LASTEXITCODE -ne 0) { throw "Failed cleaning Magento cache after branding." }
}

Write-Host "Starting Magento Agency Demo Setup..." -ForegroundColor Green

if ($Reset) {
    Write-Host "Reset mode enabled: removing containers and volumes..."
    Run-Compose @("down", "-v")
    Clear-InstallState
}

Write-Host "Starting containers..."
Run-Compose @("up", "-d")
Wait-ForDb

Write-Host "Installing Composer dependencies..."
& docker compose exec -T app git config --global --add safe.directory /var/www/html
& docker compose exec -T app composer install
if ($LASTEXITCODE -ne 0) {
    throw "Composer install failed."
}

Ensure-ThemePreviewImage

$runInstall = $Reset -or -not (Is-MagentoInstalled)

if (-not $runInstall) {
    Write-Host "Magento already installed. Checking schema/data status..."
    & docker compose exec -T app bin/magento setup:db:status > $null 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Magento is already up to date. Skipping setup:upgrade."
    } else {
        Write-Host "Changes detected. Running setup:upgrade..."
        & docker compose exec -T app bin/magento setup:upgrade
        if ($LASTEXITCODE -ne 0) {
            Write-Host "setup:upgrade failed; falling back to clean setup:install..." -ForegroundColor Yellow
            Clear-InstallState
            $runInstall = $true
        }
    }
}

if ($runInstall) {
    Write-Host "Magento not detected. Running first-time installation..."
    & docker compose exec -T app bin/magento setup:install `
        --cleanup-database `
        --base-url=http://localhost:8080/ `
        --db-host=db `
        --db-name=magento `
        --db-user=magento `
        --db-password=magento `
        --admin-firstname=Admin `
        --admin-lastname=User `
        --admin-email=admin@example.com `
        --admin-user=admin `
        --admin-password=Password123 `
        --language=en_US `
        --currency=USD `
        --timezone=America/Chicago `
        --use-rewrites=1 `
        --backend-frontname=admin `
        --search-engine=elasticsearch7 `
        --elasticsearch-host=elasticsearch `
        --elasticsearch-port=9200
    if ($LASTEXITCODE -ne 0) { throw "setup:install failed." }

    Write-Host "Warming static assets for faster storefront loading..."
    & docker compose exec -T app bin/magento setup:static-content:deploy -f en_US --theme Agency/hyva-demo
    if ($LASTEXITCODE -ne 0) { throw "static-content:deploy failed." }
}

Apply-BrandingAndTheme

Write-Host "Validating installation state..."
& docker compose exec -T app bin/magento setup:db:status
if ($LASTEXITCODE -ne 0) {
    throw "Magento database status is not healthy."
}

Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "Frontend: http://localhost:8080/"
Write-Host "Backend:  http://localhost:8080/admin (User: admin / Pass: Password123)"
Write-Host "Tip: Run './scripts/setup.ps1 -Reset' for a clean rebuild."
